# Generated by Django 6.0 on 2025-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন নম্বর')),
                ('department', models.CharField(choices=[('general', 'সাধারণ জিজ্ঞাসা'), ('media', 'মিডিয়া ও প্রেস'), ('volunteer', 'স্বেচ্ছাসেবক'), ('other', 'অন্যান্য')], max_length=50, verbose_name='বিভাগ')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রেরণের সময়')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'verbose_name_plural': 'যোগাযোগ বার্তাসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
