# Generated by Django 5.2 on 2025-12-21 13:17

from django.db import migrations


from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    PressRelease = apps.get_model('core', 'PressRelease')
    Video = apps.get_model('core', 'Video')

    for event in Event.objects.all():
        if not event.slug:
            event.slug = slugify(event.title)
            # Ensure uniqueness
            base_slug = event.slug
            count = 1
            while Event.objects.filter(slug=event.slug).exclude(pk=event.pk).exists():
                event.slug = f"{base_slug}-{count}"
                count += 1
            event.save()

    for press in PressRelease.objects.all():
        if not press.slug:
            press.slug = slugify(press.title)
            base_slug = press.slug
            count = 1
            while PressRelease.objects.filter(slug=press.slug).exclude(pk=press.pk).exists():
                press.slug = f"{base_slug}-{count}"
                count += 1
            press.save()

    for video in Video.objects.all():
        if not video.slug:
            video.slug = slugify(video.title)
            base_slug = video.slug
            count = 1
            while Video.objects.filter(slug=video.slug).exclude(pk=video.pk).exists():
                video.slug = f"{base_slug}-{count}"
                count += 1
            video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_slug_pressrelease_slug_video_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
