# Generated by Django 5.2 on 2025-12-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_image_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
