# Generated by Django 5.2 on 2026-01-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage_upazila_union'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='বিষয়')),
                ('category', models.CharField(choices=[('general', 'সাধারণ মতামত'), ('policy', 'নীতি ও ইশতেহার'), ('campaign', 'প্রচারণা'), ('suggestion', 'পরামর্শ'), ('complaint', 'অভিযোগ'), ('appreciation', 'প্রশংসা')], max_length=50, verbose_name='ধরন')),
                ('rating', models.IntegerField(blank=True, choices=[(5, 'অসাধারণ'), (4, 'ভালো'), (3, 'মাঝারি'), (2, 'উন্নতি প্রয়োজন'), (1, 'খারাপ')], null=True, verbose_name='মূল্যায়ন')),
                ('message', models.TextField(verbose_name='মতামত')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রেরণের সময়')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('is_published', models.BooleanField(default=False, verbose_name='প্রকাশিত')),
            ],
            options={
                'verbose_name': 'মতামত',
                'verbose_name_plural': 'মতামতসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
