# Generated by Django 5.2 on 2026-01-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='union',
            field=models.CharField(blank=True, choices=[('lohagara_union', 'লোহাগাড়া ইউনিয়ন'), ('padua', 'পদুয়া'), ('barahatia', 'বড়হাতিয়া'), ('amirabad', 'আমিরাবাদ'), ('adhunagar', 'আধুনগর'), ('chunati', 'চুনতি'), ('charamba', 'চরাম্বা'), ('putibila', 'পুটিবিলা'), ('kalauzan', 'কালাউজান'), ('satkania_pourashava', 'সাতকানিয়া পৌরসভা'), ('satkania_union', 'সাতকানিয়া ইউনিয়ন'), ('dhemsha', 'ঢেমশা'), ('bazalia', 'বাজালিয়া'), ('kanchana', 'কাঞ্চনা'), ('keochia', 'কেঁওচিয়া'), ('madarsha', 'মাদার্শা'), ('purba_guchchagram', 'পূর্ব গুচ্ছগ্রাম')], default='', max_length=50, verbose_name='ইউনিয়ন/পৌরসভা'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upazila',
            field=models.CharField(blank=True, choices=[('lohagara', 'লোহাগাড়া'), ('satkania', 'সাতকানিয়া')], default='', max_length=50, verbose_name='উপজেলা'),
        ),
    ]
