# Generated by Django 5.2 on 2026-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_comment_upazila_union'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
        migrations.AddField(
            model_name='comment',
            name='mobile',
            field=models.CharField(default='N/A', max_length=20, verbose_name='মোবাইল নম্বর'),
        ),
        migrations.AddField(
            model_name='comment',
            name='union',
            field=models.CharField(choices=[('paschim_dhurung', 'পশ্চিম ধুরুং'), ('purba_dhurung', 'পূর্ব ধুরুং'), ('amirabad', 'আমিরাবাদ'), ('khagaria', 'খাগরিয়া'), ('lohagara_union', 'লোহাগাড়া'), ('putibila', 'পুটিবিলা'), ('chunti', 'চুনতি'), ('adhunagar', 'আধুনগর'), ('lohagara_pourashava', 'লোহাগাড়া পৌরসভা'), ('kaliaish', 'কালিয়াইশ'), ('dharmapur', 'ধর্মপুর'), ('bazalia', 'বাজালিয়া'), ('purangar', 'পুরানগড়'), ('chadaha', 'ছদাহা'), ('satkania_union', 'সাতকানিয়া'), ('sonakania', 'সোনাকানিয়া'), ('satkania_pourashava', 'সাতকানিয়া পৌরসভা')], default='satkania_union', max_length=50, verbose_name='ইউনিয়ন/পৌরসভা'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upazila',
            field=models.CharField(choices=[('satkania', 'সাতকানিয়া'), ('lohagara', 'লোহাগাড়া')], default='satkania', max_length=50, verbose_name='উপজেলা'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ward',
            field=models.CharField(choices=[('1', '১'), ('2', '২'), ('3', '৩'), ('4', '৪'), ('5', '৫'), ('6', '৬'), ('7', '৭'), ('8', '৮'), ('9', '৯')], default='1', max_length=10, verbose_name='ওয়ার্ড'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='union',
            field=models.CharField(choices=[('lohagara_union', 'লোহাগাড়া ইউনিয়ন'), ('padua', 'পদুয়া'), ('barahatia', 'বড়হাতিয়া'), ('amirabad', 'আমিরাবাদ'), ('adhunagar', 'আধুনগর'), ('chunati', 'চুনতি'), ('charamba', 'চরম্বা'), ('putibila', 'পুটিবিলা'), ('kalauzan', 'কলাউজান'), ('charti', '১নং চরতী'), ('khagria', '২নং খাগরিয়া'), ('nalua', '৩নং নলুয়া'), ('kanchana', '৪নং কাঞ্চনা'), ('amilais', '৫নং আমিলাইষ'), ('eochia', '৬নং এওচিয়া'), ('madarsha', '৭নং মাদার্শা'), ('dhemsha', '৮নং ঢেমশা'), ('paschim_dhemsha', '৯নং পশ্চিম ঢেমশা'), ('keochia', '১০নং কেঁওচিয়া'), ('kaliaish', '১১নং কালিয়াইশ'), ('dharmapur', '১২নং ধর্মপুর'), ('bazalia', '১৩নং বাজালিয়া'), ('purangar', '১৪নং পুরানগড়'), ('chadaha', '১৫নং ছদাহা'), ('satkania_union', '১৬নং সাতকানিয়া'), ('sonakania', '১৭নং সোনাকানিয়া'), ('satkania_pourashava', 'সাতকানিয়া পৌরসভা')], max_length=50, verbose_name='ইউনিয়ন/পৌরসভা'),
        ),
    ]
