# Generated by Django 5.2 on 2026-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='মোবাইল নম্বর'),
        ),
    ]
